version: 1
formatters:
  simple:
    format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
loggers:
  clr_routing:
    level: INFO
  timm:
    level: WARNING # silence the pretrained-weights spam
  httpx:
    level: WARNING
root:
  level: INFO
  handlers: [console, file]
disable_existing_loggers: false
